version: "3.9"
services:
  backend:
    image: node:20
    working_dir: /app
    command: bash -lc "npm i && npm run dev"
    ports: ["8000:8000"]
    volumes: ["./backend:/app"]
    env_file: ["./backend/.env"]
    depends_on: [ai]
  ai:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install -r requirements.txt && python app.py"
    ports: ["5001:5001"]
    volumes: ["./ai_service:/app"]
    env_file: ["./ai_service/.env"]
  dashboard:
    image: node:20
    working_dir: /app
    command: bash -lc "npm i && npm run dev -- --host"
    ports: ["5173:5173"]
    volumes: ["./dashboard:/app"]
  website:
    image: node:20
    working_dir: /app
    command: bash -lc "npm i && npm run dev -- --host"
    ports: ["5174:5174"]
    volumes: ["./website:/app"]
